version: 2

jobs:
  build:
    working_directory: ~/work

    docker:
      - image: circleci/android:api-27-alpha

    steps:
      - checkout

      - restore_cache:
          key: cache-{{ checksum "build.gradle" }}-{{ checksum "gradle/wrapper/gradle-wrapper.properties" }}-{{ checksum "app/build.gradle" }}

      - run: ./gradlew testDebug lintDebug

      - save_cache:
          paths:
            - ~/.gradle
          key: cache-{{ checksum "build.gradle" }}-{{ checksum "gradle/wrapper/gradle-wrapper.properties" }}-{{ checksum "app/build.gradle" }}

      - store_artifacts:
          path: app/build/reports
          destination: reports

      - store_test_results:
          path: app/build/test-results
